import CreateQuestionsForQuestionBankComponent from '../components/CreateQuestionsForQuestionBankComponent'
const createQuestionsForQuestionBank=()=><CreateQuestionsForQuestionBankComponent/>

export default createQuestionsForQuestionBank;